(2023) Andrew Lock/Chapter14/A_RoutingExamples/RoutingExamples/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace RoutingExamples.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

(2023) Andrew Lock/Chapter14/A_RoutingExamples/RoutingExamples/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace RoutingExamples.Pages;

public class IndexModel : PageModel
{
    private readonly ILogger<IndexModel> _logger;

    public IndexModel(ILogger<IndexModel> logger)
    {
        _logger = logger;
    }

    public void OnGet()
    {

    }
}

(2023) Andrew Lock/Chapter14/A_RoutingExamples/RoutingExamples/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace RoutingExamples.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

(2023) Andrew Lock/Chapter14/A_RoutingExamples/RoutingExamples/Pages/ProductDetails/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

#nullable disable

namespace RoutingExamples.Pages.ProductDetails;

public class IndexModel : PageModel
{
    private readonly ProductService _service;
    public IndexModel(ProductService service)
    {
        _service = service;
    }

    public Product Selected { get; set; }

    public IActionResult OnGet(string name)
    {
        Selected = _service.GetProduct(name);
        if (Selected is null)
        {
            return NotFound();
        }
        return Page();
    }

}

(2023) Andrew Lock/Chapter14/A_RoutingExamples/RoutingExamples/Pages/Products.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace RoutingExamples.Pages;

#nullable disable

public class ProductsModel : PageModel
{
    private readonly ProductService _service;

    public ProductsModel(ProductService service)
    {
        _service = service;
    }

    [BindProperty(SupportsGet = true)]
    public string Name { get; set; }
    public Product Selected { get; set; }

    public IActionResult OnGet()
    {
        Selected = _service.GetProduct(Name);
        if(Selected is null)
        {
            return NotFound();
        }
        return Page();
    }

}

(2023) Andrew Lock/Chapter14/A_RoutingExamples/RoutingExamples/Pages/Search.cshtml.cs
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

#nullable disable

namespace RoutingExamples.Pages;

public class SearchModel : PageModel
{
    private readonly ProductService _productService;
    private readonly LinkGenerator _link;

    public SearchModel(ProductService productService, LinkGenerator link)
    {
        _productService = productService;
        _link = link;
    }

    [BindProperty, Required]
    public string SearchTerm { get; set; }
    public List<Product> Results { get; private set; }

    public void OnGet()
    {
        // Demonstrates link generation 
        var url1 = Url.Page("ProductDetails/Index", new { name = "big-widget" });
        var url2= _link.GetPathByPage("/ProductDetails/Index", values: new { name = "big-widget" });
        var url3 = _link.GetPathByPage(HttpContext, "/ProductDetails/Index", values: new { name = "big-widget" });
        var url4 = _link.GetUriByPage(
            page: "/ProductDetails/Index",
            handler: null,
            values: new { name = "big-widget" },
            scheme: "https",
            host: new HostString("example.com"));
    }

    public void OnPost()
    {
        if (ModelState.IsValid)
        {
            Results = _productService.Search(SearchTerm, StringComparison.Ordinal);
        }

    }
    public void OnPostIgnoreCase()
    {
        if (ModelState.IsValid)
        {
            Results = _productService.Search(SearchTerm, StringComparison.OrdinalIgnoreCase);
        }
    }
}

(2023) Andrew Lock/Chapter14/A_RoutingExamples/RoutingExamples/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Click on one of the product examples and view how the URL changes. Both of these products are displayed by the same Razor Page. 
        The search page shows an example of routing using the handler parameter</p>
</div>

<ul>
    <li><a asp-area="" asp-page="/Products" asp-route-name="big-widget">Big widget</a></li>
    <li><a asp-area="" asp-page="/Products" asp-route-name="super-fancy-widget">Super fancy widget</a></li>
    <li><a asp-area="" asp-page="/Search">Search</a></li>
</ul>

(2023) Andrew Lock/Chapter14/A_RoutingExamples/RoutingExamples/Pages/Products.cshtml
@page "{name}"
@model RoutingExamples.Pages.ProductsModel
@{
    ViewData["Title"] = "Products";
}

<h1>@Model.Selected.Name</h1>

<a asp-page="/ProductDetails/Index" asp-route-name="@Model.Name">View details</a>

(2023) Andrew Lock/Chapter14/A_RoutingExamples/RoutingExamples/Pages/Search.cshtml
@page "{handler?}"
@model RoutingExamples.Pages.SearchModel
@{
    ViewData["Title"] = "Search";
}

<form method="post">
    <label asp-for="SearchTerm"></label>
    <input asp-for="SearchTerm" />
    <span asp-validation-for="SearchTerm"></span>

    <button asp-page-handler="" type="submit">Search</button>
    <button asp-page-handler="IgnoreCase" type="submit">Search (ignore case)</button>
</form>

@if (Model.Results != null)
{
    if (Model.Results.Any())
    {
        <ul>
            @foreach (var product in Model.Results)
            {
                <li>@product.Name (@product.Price.ToString("c"))</li>
            }
        </ul>
    }
    else
    {
        <p>No results found for @Model.SearchTerm!</p>
    }
}